// Main process entry point

// Sentry init runs first so we catch crashes in the rest of bootstrap
// (autoUpdater wiring, native dylib loads, IPC setup, window creation).
import { initSentry } from './sentry';
initSentry();

import { app, BrowserWindow, Tray, Menu, nativeImage, ipcMain, session, shell, globalShortcut, dialog, Notification, systemPreferences, desktopCapturer } from 'electron';
import { autoUpdater } from 'electron-updater';
import WebSocket from 'ws';
import * as os from 'os';
import { initializeStream, shutdownStream } from './stream';
import { getStreamOverlay } from './stream/overlay-window';

// ============================================
// macOS Version Detection (MUST be before app.ready)
// ============================================
interface MacOSVersion {
  name: string;
  version: number;
  darwin: number;
}

function getMacOSVersion(): MacOSVersion {
  const release = os.release(); // e.g., "24.1.0" for Sequoia
  const majorVersion = parseInt(release.split('.')[0], 10);

  // Darwin version to macOS version mapping:
  // Darwin 24.x = macOS 15.x (Sequoia)
  // Darwin 23.x = macOS 14.x (Sonoma)
  // Darwin 22.x = macOS 13.x (Ventura)
  // Darwin 21.x = macOS 12.x (Monterey)

  if (majorVersion >= 24) return { name: 'Sequoia', version: 15, darwin: majorVersion };
  if (majorVersion >= 23) return { name: 'Sonoma', version: 14, darwin: majorVersion };
  if (majorVersion >= 22) return { name: 'Ventura', version: 13, darwin: majorVersion };
  if (majorVersion >= 21) return { name: 'Monterey', version: 12, darwin: majorVersion };
  return { name: 'Older', version: 11, darwin: majorVersion };
}

// B2C Personal app uses meeting bots (server-side) for recording — no local audio capture needed
const macOSInfo = process.platform === 'darwin' ? getMacOSVersion() : null;

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const STREAM_OVERLAY_WEBPACK_ENTRY: string;
declare const STREAM_OVERLAY_PRELOAD_WEBPACK_ENTRY: string;

// Type definitions
type AudioCaptureStatus = 'idle' | 'connecting' | 'capturing' | 'reconnecting' | 'error';

interface AudioCaptureConfig {
  callId?: string;
  teamId: string;
  closerId: string;
  prospectName?: string;
  sampleRate?: number; // Audio sample rate from AudioContext
}

let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;
let isQuitting = false;

// Audio capture state
let audioStatus: AudioCaptureStatus = 'idle';
let wsConnection: WebSocket | null = null;
let currentCallId: string | null = null;

// WebSocket reconnection state
let wsConnectionParams: (AudioCaptureConfig & { callId: string }) | null = null;
let wsConvexCallId: string | null = null;  // Store Convex ID for reconnection
let reconnectAttempt = 0;
let totalReconnectsThisSession = 0;
const MAX_RECONNECT_ATTEMPTS = 10;
let reconnectTimeoutId: NodeJS.Timeout | null = null;
let heartbeatIntervalId: NodeJS.Timeout | null = null;
let lastPongTime: number = Date.now();
const HEARTBEAT_INTERVAL_MS = 10000;  // 10 seconds
const HEARTBEAT_STALE_MS = 20000;     // 20 seconds
let isReconnecting = false;

// Live Chat state
let chatPollingInterval: NodeJS.Timeout | null = null;

// Pending display-media request — set by setDisplayMediaRequestHandler when
// the renderer calls getDisplayMedia, cleared by the
// 'app:select-display-media-source' IPC handler when the user picks (or
// cancels) in ScreenSharePickerModal.
let pendingDisplayMedia: {
  callback: (streams: Electron.Streams) => void;
  sources: Electron.DesktopCapturerSource[];
} | null = null;
let chatCloserId: string | null = null;
let chatTeamId: string | null = null;
let chatCloserName: string | null = null;

// Current logged-in closer ID (used in diagnostics fallback)
let currentCloserId: string | null = null;

// Current team ID (stored on bot call start, used in diagnostics)
let currentTeamId: string | null = null;

// Current theme (synced from main window, sent to the stream overlay on creation)
let currentTheme: string = 'light';

// Audio service URL - Production Railway deployment
const AUDIO_SERVICE_URL = process.env.AUDIO_SERVICE_URL || 'wss://amusing-charm-production.up.railway.app';

// Clerk configuration
const CLERK_PUBLISHABLE_KEY = process.env.CLERK_PUBLISHABLE_KEY || 'pk_test_cmVsZXZhbnQtZmluY2gtMzguY2xlcmsuYWNjb3VudHMuZGV2JA';
const CLERK_SECRET_KEY = process.env.CLERK_SECRET_KEY || 'sk_test_HlsHEnSRSzhOdHYGZMB6OdLXx00cPVHl6eY8kgT8pt';
const CLERK_FRONTEND_API = 'https://relevant-finch-38.clerk.accounts.dev';

// Custom protocol for auth callback
const PROTOCOL_NAME = 'sequ3nce-personal';

// Pending magic link verification
let pendingMagicLinkEmail: string | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 400,
    height: 600,
    minWidth: 350,
    minHeight: 500,
    titleBarStyle: 'hiddenInset',
    backgroundColor: '#ffffff',
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // Load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open window.open / <a target="_blank"> links in the system browser
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    try {
      const parsed = new URL(url);
      if (parsed.protocol === 'http:' || parsed.protocol === 'https:') {
        shell.openExternal(url);
      }
    } catch { /* ignore invalid URLs */ }
    return { action: 'deny' };
  });

  // Show window when ready — renderer sets correct size synchronously before paint
  mainWindow.once('ready-to-show', () => {
    mainWindow?.show();
  });

  // Prevent window from closing, minimize to tray instead.
  // If we're in native macOS fullscreen, hiding synchronously leaves the Space
  // black — we must exit fullscreen first and hide once the transition ends.
  mainWindow.on('close', (event) => {
    if (isQuitting) return;
    event.preventDefault();
    if (!mainWindow) return;

    if (mainWindow.isFullScreen()) {
      mainWindow.once('leave-full-screen', () => {
        mainWindow?.hide();
      });
      mainWindow.setFullScreen(false);
    } else {
      mainWindow.hide();
    }
  });

  // Open DevTools in development
  if (process.env.NODE_ENV === 'development' || process.defaultApp) {
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  }
};


const createTray = (): void => {
  // Create a simple tray icon from a data URL
  const icon = nativeImage.createFromDataURL(
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAbwAAAG8B8aLcQwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABrSURBVDiNY2AYBQMNGBkZ/1NSUhJhZGT8T4oeFHr+//+vwMDA8B8ZkKIHhYH//xkYGBgYcGkgRQ8KA+kGENKDyw1kA6J9QEgPLjfgBPj0EAXINoCQHqK8QEgPLjeQDXDpIRsQ0kNRiA8lAAApfkE9rChPUQAAAABJRU5ErkJggg=='
  );

  tray = new Tray(icon.resize({ width: 16, height: 16 }));

  const contextMenu = Menu.buildFromTemplate([
    {
      label: 'Show Sequ3nce',
      click: () => {
        mainWindow?.show();
        mainWindow?.focus();
      },
    },
    { type: 'separator' },
    {
      label: 'Quit Sequ3nce',
      click: () => {
        isQuitting = true;
        app.quit();
      },
    },
  ]);

  tray.setToolTip('Sequ3nce');
  tray.setContextMenu(contextMenu);

  // Double-click to show window
  tray.on('double-click', () => {
    mainWindow?.show();
    mainWindow?.focus();
  });
};

// Update status and notify renderer
const updateStatus = (status: AudioCaptureStatus) => {
  audioStatus = status;
  mainWindow?.webContents.send('audio:status-change', status);
  console.log(`[Main] Audio status: ${status}`);
};

// End a call in the backend (used when connection drops unexpectedly)
const endCallInBackend = async (callId: string) => {
  try {
    console.log('[Main] Ending call in backend:', callId);
    const response = await fetch('https://ideal-ram-982.convex.site/endCall', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ callId, reason: 'connection_lost' }),
    });
    if (!response.ok) {
      console.error('[Main] Failed to end call in backend:', await response.text());
    } else {
      console.log('[Main] Call ended in backend successfully');
    }
  } catch (err) {
    console.error('[Main] Error ending call in backend:', err);
  }
};

// Connect to WebSocket server (with reconnection support)
const connectWebSocket = (config: AudioCaptureConfig & { callId: string; convexCallId?: string; isReconnect?: boolean }): Promise<boolean> => {
  return new Promise((resolve) => {
    // Store params for potential reconnection (only on initial connection)
    if (!config.isReconnect) {
      wsConnectionParams = config;
    }

    console.log(`[Main] Connecting to WebSocket: ${AUDIO_SERVICE_URL} (isReconnect: ${config.isReconnect || false})`);

    try {
      wsConnection = new WebSocket(AUDIO_SERVICE_URL);

      const timeout = setTimeout(() => {
        console.error('[Main] WebSocket connection timeout');
        wsConnection?.close();
        resolve(false);
      }, 10000);

      wsConnection.on('open', () => {
        clearTimeout(timeout);
        console.log('[Main] WebSocket connected');

        // Send metadata including sample rate and reconnection fields
        const metadata = {
          callId: config.callId,
          teamId: config.teamId,
          closerId: config.closerId,
          prospectName: config.prospectName,
          sampleRate: config.sampleRate || 48000, // Include sample rate for WAV header
          convexCallId: config.convexCallId,  // Include for reconnection
          isReconnect: config.isReconnect || false,
        };

        wsConnection!.send(JSON.stringify(metadata));
        console.log('[Main] Sent metadata:', metadata);

        // Start heartbeat for connection health monitoring
        startHeartbeat();
      });

      wsConnection.on('message', (data) => {
        try {
          const message = JSON.parse(data.toString());
          console.log('[Main] WebSocket message:', message);

          if (message.status === 'ready') {
            console.log('[Main] Server ready, can start streaming');

            // CRITICAL: Use the Convex-generated callId for all operations
            // The server returns convexCallId which is the actual database ID
            if (message.convexCallId) {
              console.log('[Main] Updating callId from:', currentCallId, 'to Convex ID:', message.convexCallId);
              wsConvexCallId = message.convexCallId;  // Store for reconnection
              currentCallId = message.convexCallId;

              // Notify renderer of the correct call ID
              mainWindow?.webContents.send('audio:call-id-updated', message.convexCallId);
            }

            resolve(true);
          } else if (message.type === 'pong') {
            // Update last pong time for heartbeat health check
            lastPongTime = Date.now();
          } else if (message.type === 'silence_warning') {
            // Handle silence warning from server
            console.log('[Main] Silence warning:', message.silenceDuration, 'seconds');
            mainWindow?.webContents.send('audio:silence-warning', {
              silenceDuration: message.silenceDuration,
              message: message.message,
            });
            // Trigger reconnect if silence exceeds 60 seconds
            if (message.silenceDuration >= 60 && !isReconnecting) {
              console.log('[Main] Extended silence detected, attempting reconnect');
              handleStaleConnection();
            }
          } else if (message.error) {
            console.error('[Main] Server error:', message.error);
            mainWindow?.webContents.send('audio:error', message.error);
            resolve(false);
          }
        } catch (err) {
          console.error('[Main] Failed to parse message:', err);
        }
      });

      wsConnection.on('error', (err) => {
        clearTimeout(timeout);
        console.error('[Main] WebSocket error:', err);
        mainWindow?.webContents.send('audio:error', `Connection error: ${err.message}`);
        resolve(false);
      });

      wsConnection.on('close', () => {
        console.log('[Main] WebSocket closed');
        stopHeartbeat();

        // If we were capturing and not already reconnecting, attempt reconnect
        if (audioStatus === 'capturing' && !isReconnecting) {
          console.log('[Main] Connection dropped during capture, attempting reconnect');
          attemptReconnect();
        } else if (!isReconnecting) {
          // Normal close (not during capture or already reconnecting)
          wsConnection = null;
        }
      });
    } catch (err) {
      console.error('[Main] Failed to create WebSocket:', err);
      resolve(false);
    }
  });
};

// Send audio data to WebSocket
const sendAudioData = (data: Buffer) => {
  if (wsConnection && wsConnection.readyState === WebSocket.OPEN) {
    wsConnection.send(data);
  }
};

// Close WebSocket connection
const closeWebSocket = async () => {
  if (wsConnection) {
    if (wsConnection.readyState === WebSocket.OPEN) {
      // Send end message
      wsConnection.send(JSON.stringify({ type: 'end' }));
      // Wait a bit for message to be sent
      await new Promise((resolve) => setTimeout(resolve, 500));
    }
    wsConnection.close();
    wsConnection = null;
  }
};

// ==================== WebSocket Reconnection Functions ====================

// Start heartbeat ping/pong to detect stale connections
const startHeartbeat = () => {
  stopHeartbeat();
  lastPongTime = Date.now();

  heartbeatIntervalId = setInterval(() => {
    if (wsConnection?.readyState === WebSocket.OPEN) {
      // Check for stale connection
      if (Date.now() - lastPongTime > HEARTBEAT_STALE_MS) {
        console.log('[Main] Connection stale - no pong for 20s, triggering reconnect');
        handleStaleConnection();
        return;
      }
      // Send ping
      wsConnection.send(JSON.stringify({ type: 'ping' }));
    }
  }, HEARTBEAT_INTERVAL_MS);
};

// Stop heartbeat timer
const stopHeartbeat = () => {
  if (heartbeatIntervalId) {
    clearInterval(heartbeatIntervalId);
    heartbeatIntervalId = null;
  }
};

// Handle stale connection - close and attempt reconnect
const handleStaleConnection = () => {
  if (isReconnecting) return;

  stopHeartbeat();
  if (wsConnection) {
    wsConnection.close();
    wsConnection = null;
  }
  attemptReconnect();
};

// Attempt to reconnect with exponential backoff
const attemptReconnect = async () => {
  if (!wsConnectionParams || reconnectAttempt >= MAX_RECONNECT_ATTEMPTS) {
    console.log('[Main] Max reconnect attempts reached or no params');
    updateStatus('error');
    mainWindow?.webContents.send('audio:error', 'Connection lost - max reconnect attempts reached');
    if (currentCallId) {
      endCallInBackend(currentCallId);
    }
    cleanupReconnectState();
    return;
  }

  isReconnecting = true;
  reconnectAttempt++;

  // Exponential backoff: 1s, 2s, 4s, 8s... max 30s
  const delay = Math.min(1000 * Math.pow(2, reconnectAttempt - 1), 30000);

  console.log(`[Main] Reconnect attempt ${reconnectAttempt}/${MAX_RECONNECT_ATTEMPTS} in ${delay}ms`);
  updateStatus('reconnecting');
  mainWindow?.webContents.send('audio:reconnecting', { attempt: reconnectAttempt, maxAttempts: MAX_RECONNECT_ATTEMPTS });

  reconnectTimeoutId = setTimeout(async () => {
    try {
      const success = await connectWebSocket({
        ...wsConnectionParams!,
        convexCallId: wsConvexCallId || undefined,
        isReconnect: true,
      });

      if (success) {
        console.log('[Main] Reconnected successfully');
        reconnectAttempt = 0;
        totalReconnectsThisSession++;
        isReconnecting = false;
        updateStatus('capturing');
        mainWindow?.webContents.send('audio:reconnected');
      } else {
        attemptReconnect();
      }
    } catch (err) {
      console.error('[Main] Reconnect failed:', err);
      attemptReconnect();
    }
  }, delay);
};

// Clean up all reconnection state
const cleanupReconnectState = () => {
  isReconnecting = false;
  reconnectAttempt = 0;
  wsConnectionParams = null;
  wsConvexCallId = null;
  if (reconnectTimeoutId) {
    clearTimeout(reconnectTimeoutId);
    reconnectTimeoutId = null;
  }
  stopHeartbeat();
};

// ==================== Auth Functions ====================

// Web app URL for auth
const WEB_APP_URL = process.env.WEB_APP_URL || 'https://sequ3nce.ai';

// Send magic link - opens browser to web app's auth page
async function sendMagicLink(email: string): Promise<{ success: boolean; error?: string }> {
  try {
    console.log('[Auth] Opening browser for magic link auth:', email);
    pendingMagicLinkEmail = email;

    // Build the auth URL
    const authUrl = new URL(`${WEB_APP_URL}/desktop-auth`);
    authUrl.searchParams.set('email', email);
    authUrl.searchParams.set('redirect', `${PROTOCOL_NAME}://auth-callback`);

    // Open the browser to the auth page
    shell.openExternal(authUrl.toString());

    return { success: true };
  } catch (error) {
    console.error('[Auth] Error opening auth URL:', error);
    return {
      success: false,
      error: 'Failed to open login page. Please try again.'
    };
  }
}

// Verify session token
async function verifySession(token: string): Promise<boolean> {
  try {
    // For now, just check if the token exists and is non-empty
    // In production, you'd verify with Clerk's API
    return token && token.length > 0;
  } catch (error) {
    console.error('[Auth] Error verifying session:', error);
    return false;
  }
}

// Sign out
async function signOut(): Promise<void> {
  // Clear any stored session data
  pendingMagicLinkEmail = null;
}

// Handle the auth callback from the custom protocol
function handleAuthCallback(url: string): void {
  console.log('[Auth] Handling callback URL:', url);

  try {
    const parsedUrl = new URL(url);

    // Check for error
    const error = parsedUrl.searchParams.get('error');
    if (error) {
      console.error('[Auth] Auth error:', error);
      mainWindow?.webContents.send('auth:callback', { error: 'Authentication failed. Please try again.' });
      return;
    }

    // Get the email from the callback
    const email = parsedUrl.searchParams.get('email') || pendingMagicLinkEmail;

    // Check for token or session
    const token = parsedUrl.searchParams.get('token') ||
                  parsedUrl.searchParams.get('__clerk_ticket') ||
                  'authenticated'; // Fallback token if link was clicked

    if (token && email) {
      console.log('[Auth] Auth successful for:', email);
      // Update the pending email
      pendingMagicLinkEmail = email;
      mainWindow?.webContents.send('auth:callback', { token, email });
    } else if (token) {
      console.log('[Auth] Auth successful (no email in callback)');
      mainWindow?.webContents.send('auth:callback', { token });
    } else {
      console.error('[Auth] No token in callback');
      mainWindow?.webContents.send('auth:callback', { error: 'Invalid callback. Please try again.' });
    }
  } catch (error) {
    console.error('[Auth] Error parsing callback URL:', error);
    mainWindow?.webContents.send('auth:callback', { error: 'Invalid callback. Please try again.' });
  }
}

/**
 * Handle sequ3nce-personal://calendar-connected deep link.
 * Sent from the OAuth success page after Google Calendar authorization.
 */
function handleCalendarConnected(url: string): void {
  console.log('[Calendar] Handling calendar-connected callback:', url);
  try {
    const parsedUrl = new URL(url);
    const closerId = parsedUrl.searchParams.get('closerId');
    if (closerId) {
      mainWindow?.webContents.send('calendar:connected', { closerId });
    }
  } catch (error) {
    console.error('[Calendar] Error parsing calendar-connected URL:', error);
  }
}

// ==================== IPC Handlers ====================

// Set up IPC handlers
const setupIpcHandlers = (): void => {
  console.log('[Main] Setting up IPC handlers...');

  // ---- Auth IPC Handlers ----

  ipcMain.handle('auth:send-magic-link', async (_event, email: string) => {
    return sendMagicLink(email);
  });

  ipcMain.handle('auth:verify-session', async (_event, token: string) => {
    return verifySession(token);
  });

  ipcMain.handle('auth:sign-out', async () => {
    return signOut();
  });

  // Audio IPC handlers removed — B2C Personal app uses meeting bots only (no local audio capture)

  // Set dock/taskbar badge count (macOS dock badge, Windows taskbar overlay)
  ipcMain.handle('app:set-badge-count', (_event, count: number) => {
    app.setBadgeCount(count);
  });

  // Request camera + microphone access from the OS. On macOS, this is the
  // explicit path to trigger the system permission dialog — Electron's Chromium
  // layer silently fails getUserMedia without it on newer macOS versions.
  // On non-macOS platforms we resolve true (no OS gate, Chromium handles it).
  ipcMain.handle('app:request-media-access', async () => {
    if (process.platform !== 'darwin') {
      return { camera: true, microphone: true };
    }
    const camera = await systemPreferences.askForMediaAccess('camera');
    const microphone = await systemPreferences.askForMediaAccess('microphone');
    return { camera, microphone };
  });

  // Screen recording permission on macOS is a separate TCC gate from camera/mic.
  // There's no askForMediaAccess('screen') API — the first getDisplayMedia()
  // attempt registers the app in System Settings → Privacy & Security → Screen
  // & System Audio Recording (default: denied). User must manually enable +
  // restart the app. Without this check the share fails silently.
  ipcMain.handle('app:get-screen-access-status', () => {
    if (process.platform !== 'darwin') return 'granted';
    return systemPreferences.getMediaAccessStatus('screen');
  });

  // Jump the user straight to the Screen Recording settings pane so they
  // don't have to hunt through System Settings. Closer to one-click grant.
  ipcMain.handle('app:open-screen-settings', () => {
    if (process.platform !== 'darwin') return false;
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { shell } = require('electron');
    void shell.openExternal(
      'x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture'
    );
    return true;
  });

  // Source list for the in-app screen-share picker. Returns thumbnails as
  // data URLs so the renderer can render them without piping native image
  // objects across the IPC boundary. Coaching-call screen share fetches
  // sources via this handler, shows the picker, then passes the chosen
  // source's id to Daily as `chromeMediaSourceId` — Daily then captures
  // and publishes via its OWN pipeline (which is what was missing when we
  // tried passing pre-captured streams to startScreenShare({ mediaStream })).
  ipcMain.handle('app:get-screen-sources', async () => {
    const sources = await desktopCapturer.getSources({
      types: ['screen', 'window'],
      thumbnailSize: { width: 320, height: 200 },
      fetchWindowIcons: true,
    });
    return sources.map((s) => ({
      id: s.id,
      name: s.name,
      type: s.id.startsWith('screen:') ? ('screen' as const) : ('window' as const),
      thumbnail: s.thumbnail.toDataURL(),
      appIcon: s.appIcon && !s.appIcon.isEmpty() ? s.appIcon.toDataURL() : null,
    }));
  });

  // Resolves any pending getDisplayMedia request. Kept as a safety net for
  // code paths that call getDisplayMedia directly (none today, but future-
  // proofs against e.g. a role-play feature using browser APIs). For the
  // coaching screen share, the picker is shown via a different path — this
  // handler is rarely invoked.
  ipcMain.handle('app:select-display-media-source', (_evt, sourceId: string | null) => {
    if (!pendingDisplayMedia) return;
    const { callback, sources } = pendingDisplayMedia;
    pendingDisplayMedia = null;
    if (sourceId === null) {
      callback({});
      return;
    }
    const picked = sources.find((s) => s.id === sourceId);
    callback(picked ? { video: picked } : {});
  });

  // Get app version
  ipcMain.handle('app:get-version', () => {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const pkg = require('../package.json');
    return pkg.version;
  });

  // Get platform info (includes OS version for debugging)
  ipcMain.handle('app:get-platform', () => {
    return {
      platform: process.platform,
      arch: process.arch,
      osRelease: os.release(), // Darwin version (e.g., "24.1.0" for Sequoia)
    };
  });

  // Collect diagnostics from main process for diagnostic reports
  ipcMain.handle('diagnostics:collect', async () => {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const pkg = require('../package.json');

    // System info
    let hardwareModel = 'unknown';
    try {
      if (process.platform === 'darwin') {
        hardwareModel = require('child_process').execSync('sysctl -n hw.model', { timeout: 3000 }).toString().trim();
      } else if (process.platform === 'win32') {
        const wmicOutput = require('child_process').execSync('wmic computersystem get model', { timeout: 3000 }).toString();
        hardwareModel = wmicOutput.split('\n')[1]?.trim() || 'unknown';
      }
    } catch { /* ignore */ }

    let osVersion = '';
    try {
      osVersion = typeof os.version === 'function' ? os.version() : '';
    } catch { /* ignore */ }

    const system = {
      platform: process.platform,
      arch: process.arch,
      osRelease: os.release(),
      osVersion,
      macOSVersion: macOSInfo ? `${macOSInfo.name} ${macOSInfo.version}` : undefined,
      chipType: process.arch === 'arm64' ? 'Apple Silicon' : 'Intel',
      hardwareModel,
      cpuModel: os.cpus()[0]?.model || 'unknown',
      ramTotalGB: +(os.totalmem() / (1024 ** 3)).toFixed(1),
      ramAvailableGB: +(os.freemem() / (1024 ** 3)).toFixed(1),
      appVersion: pkg.version,
      appUptime: Math.round(process.uptime()),
      electronVersion: process.versions.electron,
      chromeVersion: process.versions.chrome,
      openWindowCount: [mainWindow, getStreamOverlay()]
        .filter(w => w && !w.isDestroyed()).length,
    };

    // WebSocket state
    const websocket = {
      connectionState: wsConnection
        ? (['CONNECTING', 'OPEN', 'CLOSING', 'CLOSED'][wsConnection.readyState] || 'unknown')
        : 'none',
      reconnectAttempt,
      isReconnecting,
      lastPongSecondsAgo: Math.round((Date.now() - lastPongTime) / 1000),
      reconnectionCountThisSession: totalReconnectsThisSession,
      audioServiceUrl: AUDIO_SERVICE_URL,
    };

    // Audio state (local capture not used in B2C — meeting bots handle recording)
    const audio = {
      captureStatus: audioStatus,
      currentCallId: currentCallId || undefined,
      hasActiveConnection: !!wsConnection,
      isCapturing: audioStatus === 'capturing',
    };

    // Call state
    const call = {
      currentCallId: currentCallId || undefined,
      convexCallId: wsConvexCallId || undefined,
      recordingState: audioStatus,
      closerId: wsConnectionParams?.closerId || currentCloserId || undefined,
      teamId: wsConnectionParams?.teamId || currentTeamId || undefined,
    };

    // Context
    const context = {
      theme: currentTheme,
      chatPollingActive: !!chatPollingInterval,
    };

    return { system, websocket, audio, call, context };
  });

  // Resize main window (used when switching between legacy and hub mode)
  ipcMain.handle('app:set-window-size', (_event, width: number, height: number) => {
    if (mainWindow) {
      mainWindow.setMinimumSize(
        width >= 900 ? 900 : 350,
        width >= 900 ? 600 : 500
      );
      mainWindow.setSize(width, height);
      mainWindow.center();
      console.log(`[Main] Window resized to ${width}x${height}`);
    }
  });

  // Get current theme for stream overlay (avoids race with IPC listener on mount)
  ipcMain.handle('stream:get-theme', () => {
    return currentTheme;
  });

  // ---- Bot Call IPC Handlers ----

  ipcMain.handle('bot:call-started', async (_event, data: { callId: string; teamId: string; closerId: string; closerName: string; prospectName?: string; meetingTitle?: string; botId?: string }) => {
    console.log('[Main] Bot call started:', data.callId);
    // Store call context for chat + diagnostics
    currentCallId = data.callId;
    currentTeamId = data.teamId;
    chatCloserId = data.closerId;
    chatCloserName = data.closerName;
  });

  ipcMain.handle('bot:call-ended', async (_event, data: { callId: string; closerId: string; closerName?: string; teamId?: string; prospectName?: string }) => {
    console.log('[Main] Bot call ended:', data.callId);
    currentCallId = null;
  });

  // ---- Theme Sync IPC Handler ----

  ipcMain.handle('app:theme-changed', (_event, theme: string) => {
    // Store current theme so we can send it to newly created windows
    currentTheme = theme;
    const streamOverlay = getStreamOverlay();
    if (streamOverlay && !streamOverlay.isDestroyed()) {
      streamOverlay.webContents.send('theme-changed', theme);
    }
  });

  // ---- Live Chat IPC Handlers ----

  // Get messages for closer
  ipcMain.handle('chat:get-messages', async (_event, closerId: string, limit?: number) => {
    try {
      const response = await fetch(
        `https://ideal-ram-982.convex.site/getMessagesForCloser?closerId=${encodeURIComponent(closerId)}&limit=${limit || 100}`
      );
      if (!response.ok) return [];
      return await response.json();
    } catch (error) {
      console.error('[Main] Error getting chat messages:', error);
      return [];
    }
  });

  // Send message from closer
  ipcMain.handle('chat:send-message', async (_event, teamId: string, closerId: string, closerName: string, message: string) => {
    try {
      const response = await fetch('https://ideal-ram-982.convex.site/sendMessage', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          teamId,
          senderType: 'closer',
          senderCloserId: closerId,
          senderName: closerName,
          recipientType: 'manager',
          message,
        }),
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(errorText || 'Failed to send message');
      }
      return await response.json();
    } catch (error) {
      console.error('[Main] Error sending chat message:', error);
      throw error;
    }
  });

  // Mark all messages as read
  ipcMain.handle('chat:mark-all-read', async (_event, closerId: string) => {
    try {
      const response = await fetch('https://ideal-ram-982.convex.site/markAllAsReadForCloser', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ closerId }),
      });
      if (!response.ok) throw new Error('Failed to mark messages as read');

      // Note: Don't clear dock badge here - let the polling loop handle it
      // based on the actual unread count from the API

      return await response.json();
    } catch (error) {
      console.error('[Main] Error marking messages as read:', error);
      throw error;
    }
  });

  // Get unread count
  ipcMain.handle('chat:get-unread-count', async (_event, closerId: string) => {
    try {
      const response = await fetch(
        `https://ideal-ram-982.convex.site/getUnreadCountForCloser?closerId=${encodeURIComponent(closerId)}`
      );
      if (!response.ok) return 0;
      const data = await response.json();
      const count = data.count || 0;

      // Update dock badge
      if (process.platform === 'darwin') {
        app.dock.setBadge(count > 0 ? String(count) : '');
      }

      return count;
    } catch (error) {
      console.error('[Main] Error getting unread count:', error);
      return 0;
    }
  });

  // Get latest unread message (for notification)
  ipcMain.handle('chat:get-latest-unread', async (_event, closerId: string) => {
    try {
      const response = await fetch(
        `https://ideal-ram-982.convex.site/getLatestUnreadForCloser?closerId=${encodeURIComponent(closerId)}`
      );
      if (!response.ok) return null;
      return await response.json();
    } catch (error) {
      console.error('[Main] Error getting latest unread:', error);
      return null;
    }
  });

  // Start polling for messages
  ipcMain.handle('chat:start-polling', (_event, closerId: string, teamId: string, closerName: string, intervalMs?: number) => {
    console.log('[Main] Starting chat polling for closer:', closerId);

    // Stop existing polling
    if (chatPollingInterval) {
      clearInterval(chatPollingInterval);
    }

    chatCloserId = closerId;
    chatTeamId = teamId;
    chatCloserName = closerName;

    const pollInterval = intervalMs || 2500;  // Default 2.5 seconds
    let lastSeenMessageId: string | null = null;

    chatPollingInterval = setInterval(async () => {
      try {
        // Get unread count
        const countResponse = await fetch(
          `https://ideal-ram-982.convex.site/getUnreadCountForCloser?closerId=${encodeURIComponent(closerId)}`
        );
        if (countResponse.ok) {
          const data = await countResponse.json();
          const count = data.count || 0;

          // Update dock badge
          if (process.platform === 'darwin') {
            app.dock.setBadge(count > 0 ? String(count) : '');
          }

          // Notify renderer
          mainWindow?.webContents.send('chat:unread-count-changed', count);
        }

        // Get latest unread for notification
        const latestResponse = await fetch(
          `https://ideal-ram-982.convex.site/getLatestUnreadForCloser?closerId=${encodeURIComponent(closerId)}`
        );
        if (latestResponse.ok) {
          const latest = await latestResponse.json();
          if (latest && latest._id !== lastSeenMessageId) {
            lastSeenMessageId = latest._id;
            // Notify renderer of new message
            mainWindow?.webContents.send('chat:new-message', latest);

            // Show notification for new messages from manager
            if (latest.senderType === 'manager') {
              console.log('[Main] Showing notification for new chat message from:', latest.senderName);

              // Play system beep sound (reliable fallback)
              shell.beep();

              // Show native notification
              const notification = new Notification({
                title: 'New Message',
                body: `${latest.senderName}: ${latest.message?.substring(0, 100) || 'Sent you a message'}`,
                silent: true, // Don't play notification sound since we're using shell.beep()
              });

              // When notification is clicked, show the main window
              notification.on('click', () => {
                if (mainWindow) {
                  mainWindow.show();
                  mainWindow.focus();
                }
              });

              notification.show();
            }
          }
        }
      } catch (error) {
        console.error('[Main] Chat polling error:', error);
      }
    }, pollInterval);

    return { success: true };
  });

  // Stop polling
  ipcMain.handle('chat:stop-polling', () => {
    console.log('[Main] Stopping chat polling');
    if (chatPollingInterval) {
      clearInterval(chatPollingInterval);
      chatPollingInterval = null;
    }
    chatCloserId = null;
    chatTeamId = null;
    chatCloserName = null;

    // Clear dock badge
    if (process.platform === 'darwin') {
      app.dock.setBadge('');
    }

    return { success: true };
  });

  // Get closer info for chat
  ipcMain.handle('chat:get-closer-info', () => {
    return {
      closerId: chatCloserId,
      teamId: chatTeamId,
      closerName: chatCloserName,
    };
  });

  console.log('[Main] IPC handlers set up');
};

// Register the custom protocol handler
const registerProtocol = () => {
  // Register as the default protocol handler for sequ3nce://
  if (process.defaultApp) {
    if (process.argv.length >= 2) {
      app.setAsDefaultProtocolClient(PROTOCOL_NAME, process.execPath, [process.argv[1]]);
    }
  } else {
    app.setAsDefaultProtocolClient(PROTOCOL_NAME);
  }

  console.log(`[Main] Registered protocol handler for ${PROTOCOL_NAME}://`);
};

// This method will be called when Electron has finished initialization
app.whenReady().then(() => {
  // Register protocol first
  registerProtocol();

  createWindow();
  createTray();
  setupIpcHandlers();
  setupAutoUpdater(); // Initialize auto-updater

  // B2C Personal app uses server-side meeting bots — no local audio permissions needed

  // Initialize Sequ3nce Stream (hold-to-talk dictation)
  // Wrapped in try/catch so any Stream failure cannot break the rest of the app.
  try {
    initializeStream();
  } catch (err) {
    console.error('[Main] initializeStream failed:', err);
  }

  // Grant permission requests from renderers for the APIs video calling needs.
  // Electron defaults to *deny* on all permission prompts, so Daily.co's
  // getUserMedia() + getDisplayMedia() calls fail silently without this.
  // We scope the grant narrowly — only the permissions an in-app video call
  // legitimately needs. macOS still enforces its own system-level prompts on
  // top of this (Camera/Microphone/Screen Recording under System Settings).
  session.defaultSession.setPermissionRequestHandler(
    (_webContents, permission, callback) => {
      const allowed = new Set([
        'media',                      // camera + mic (getUserMedia)
        'display-capture',            // screen sharing (getDisplayMedia)
        // navigator.clipboard.writeText() — without this, the share-modal
        // Copy button silently fails when Chromium routes the write through
        // the permission system (post-await timing in handleGenerate, focus
        // edge cases). Restores the pre-handler default-grant for clipboard.
        'clipboard-sanitized-write',
      ]);
      callback(allowed.has(permission));
    }
  );

  // Display-media request handler — fires when the renderer calls
  // navigator.mediaDevices.getDisplayMedia() (which Daily's startScreenShare
  // does internally). We DEFER the callback: store it + the source list,
  // notify the renderer via 'display-media:request' so it can show our
  // ScreenSharePickerModal, then wait for the renderer to pick (or cancel)
  // via the 'app:select-display-media-source' IPC handler above. That call
  // fires the stored callback with the chosen source, which gives Daily a
  // proper MediaStream and the share actually streams to viewers.
  //
  // useSystemPicker is FALSE because (a) it requires macOS 15 Sequoia and
  // (b) when active it suppresses our callback entirely on macOS 15+. Our
  // custom picker works the same on every macOS version.
  session.defaultSession.setDisplayMediaRequestHandler(
    async (_request, callback) => {
      try {
        const sources = await desktopCapturer.getSources({
          types: ['screen', 'window'],
          thumbnailSize: { width: 320, height: 200 },
          fetchWindowIcons: true,
        });
        // If a previous picker is still pending (e.g. user clicked Share
        // twice) cancel it cleanly before replacing.
        if (pendingDisplayMedia) {
          pendingDisplayMedia.callback({});
        }
        pendingDisplayMedia = { callback, sources };
        const win = mainWindow ?? BrowserWindow.getAllWindows()[0];
        if (!win) {
          // No renderer to ask — fall back to first source.
          pendingDisplayMedia = null;
          callback(sources[0] ? { video: sources[0] } : {});
          return;
        }
        win.webContents.send(
          'display-media:request',
          sources.map((s) => ({
            id: s.id,
            name: s.name,
            type: s.id.startsWith('screen:') ? 'screen' : 'window',
            thumbnail: s.thumbnail.toDataURL(),
            appIcon: s.appIcon && !s.appIcon.isEmpty() ? s.appIcon.toDataURL() : null,
          })),
        );
      } catch (err) {
        console.error('[setDisplayMediaRequestHandler] failed:', err);
        callback({});
      }
    },
    { useSystemPicker: false }
  );

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    } else {
      mainWindow?.show();
    }
  });
});

// Handle protocol URL on macOS
app.on('open-url', (event, url) => {
  event.preventDefault();
  console.log('[Main] Received protocol URL:', url);

  if (url.startsWith(`${PROTOCOL_NAME}://auth-callback`)) {
    handleAuthCallback(url);
  } else if (url.startsWith(`${PROTOCOL_NAME}://calendar-connected`)) {
    handleCalendarConnected(url);
  }

  // Focus the main window
  if (mainWindow) {
    if (mainWindow.isMinimized()) mainWindow.restore();
    mainWindow.focus();
  }
});

// Handle protocol URL on Windows (single instance)
const gotTheLock = app.requestSingleInstanceLock();

if (!gotTheLock) {
  app.quit();
} else {
  app.on('second-instance', (event, commandLine) => {
    // Someone tried to run a second instance, we should focus our window
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }

    // Handle the protocol URL on Windows
    const url = commandLine.find((arg) => arg.startsWith(`${PROTOCOL_NAME}://`));
    if (url) {
      console.log('[Main] Received protocol URL from second instance:', url);
      if (url.startsWith(`${PROTOCOL_NAME}://auth-callback`)) {
        handleAuthCallback(url);
      } else if (url.startsWith(`${PROTOCOL_NAME}://calendar-connected`)) {
        handleCalendarConnected(url);
      }
    }
  });
}

// Quit when all windows are closed, except on macOS
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// Handle before quit
app.on('before-quit', async () => {
  isQuitting = true;
  globalShortcut.unregisterAll();
  try {
    shutdownStream();
  } catch (err) {
    console.error('[Main] shutdownStream failed:', err);
  }
  await closeWebSocket();
});

// ==================== Auto-Update ====================

// Configure auto-updater
autoUpdater.autoDownload = true;
autoUpdater.autoInstallOnAppQuit = true;

// Use generic provider with our own update server to avoid
// "Latest" release collision between B2B and B2C apps in the same repo.
// The /api/updates/personal endpoint finds the latest personal-v* release.
autoUpdater.setFeedURL({
  provider: 'generic',
  url: 'https://www.sequ3nce.ai/api/updates/personal',
});
// Do NOT set autoUpdater.channel — the default "latest" channel makes
// electron-updater request latest-mac.yml / latest.yml, which matches
// the manifest filenames in the GitHub release assets.

// Set up auto-updater event handlers
function setupAutoUpdater() {
  autoUpdater.on('checking-for-update', () => {
    console.log('[AutoUpdate] Checking for updates...');
  });

  autoUpdater.on('update-available', (info) => {
    console.log('[AutoUpdate] Update available:', info.version);
    // Notify the renderer that an update is available
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('update:available', info);
    }
  });

  autoUpdater.on('update-not-available', (info) => {
    console.log('[AutoUpdate] App is up to date:', info.version);
  });

  autoUpdater.on('download-progress', (progress) => {
    console.log(`[AutoUpdate] Download progress: ${progress.percent.toFixed(1)}%`);
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('update:progress', progress);
    }
  });

  autoUpdater.on('update-downloaded', (info) => {
    console.log('[AutoUpdate] Update downloaded:', info.version);

    // Only show dialog if window is still valid
    if (mainWindow && !mainWindow.isDestroyed()) {
      dialog.showMessageBox(mainWindow, {
        type: 'info',
        title: 'Update Ready',
        message: `A new version (${info.version}) has been downloaded.`,
        detail: 'Restart now to apply the update?',
        buttons: ['Restart Now', 'Later'],
        defaultId: 0,
      }).then((result) => {
        if (result.response === 0) {
          isQuitting = true;
          autoUpdater.quitAndInstall();
        }
      });
    } else {
      // Window was closed, install on next launch
      console.log('[AutoUpdate] Window destroyed, update will install on next launch');
    }
  });

  autoUpdater.on('error', (error) => {
    console.error('[AutoUpdate] Error:', error);
  });

  // Check for updates on startup (after a short delay)
  setTimeout(() => {
    autoUpdater.checkForUpdates().catch((err) => {
      console.error('[AutoUpdate] Failed to check for updates:', err);
    });
  }, 5000);

  // Check for updates every 4 hours
  setInterval(() => {
    autoUpdater.checkForUpdates().catch((err) => {
      console.error('[AutoUpdate] Failed to check for updates:', err);
    });
  }, 4 * 60 * 60 * 1000);
}

// IPC handler for manual update check
ipcMain.handle('update:check', async () => {
  try {
    const result = await autoUpdater.checkForUpdates();
    return { success: true, version: result?.updateInfo?.version };
  } catch (error) {
    console.error('[AutoUpdate] Manual check failed:', error);
    return { success: false, error: String(error) };
  }
});

// IPC handler for installing update
ipcMain.handle('update:install', () => {
  isQuitting = true;
  autoUpdater.quitAndInstall();
});
