"use node";

// ============================================================================
// Setter Data — Close CRM connection + funnel detection.
//
// Close connects via a pasted API key (no OAuth):
//   - connectClose: validate the key, characterize the funnel, encrypt +
//     persist the install (one CRM per team). The self-serve flow the client
//     drives from the Setter Data settings tab.
//   - detectFunnel: read-only funnel characterization (also used at connect).
// ============================================================================

import { action, internalAction } from "./_generated/server";
import { internal } from "./_generated/api";
import { v } from "convex/values";
import { closeFetch } from "./setterCloseClient";
import { encryptApiKey } from "./lib/encrypt";

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Read-only funnel characterization for a Close org — powers the "here's what
 * we detected about your funnel" transparency summary.
 */
async function probeFunnel(key: string): Promise<any> {
  const me = await closeFetch<any>(key, "/me/");
  const org = (me.organizations || [])[0] || {};
  const role = (me.memberships || []).map((m: any) => m.role_id).join(",");

  const usersPage = await closeFetch<any>(key, "/user/", { query: { _limit: 100 } });

  const cfs = await closeFetch<any>(key, "/custom_field/lead/", { query: { _limit: 200 } });
  const roleLikeFields = (cfs.data || [])
    .filter((f: any) => /setter|closer|team\s*member|dm\b/i.test(f.name || ""))
    .map((f: any) => ({ name: f.name, type: f.type }));

  const calls = await closeFetch<any>(key, "/activity/call/", { query: { _limit: 100 } });
  const cd: any[] = calls.data || [];
  const outbound = cd.filter((c) => c.direction === "outbound");
  const attributed = cd.filter((c) => c.user_id);
  const withRecording = cd.filter((c) => c.has_recording);
  const dispositions: Record<string, number> = {};
  for (const c of cd) {
    const d = c.disposition || "(none)";
    dispositions[d] = (dispositions[d] || 0) + 1;
  }
  const powerDialerDetected = cd.some((c) => c.dialer_id);

  let transcriptsAvailable = false;
  if (withRecording.length > 0) {
    const t = await closeFetch<any>(key, "/activity/call/", {
      query: { _limit: 10, _fields: "id,has_recording,recording_transcript" },
    });
    transcriptsAvailable = (t.data || []).some((c: any) => c.recording_transcript);
  }

  const meetings = await closeFetch<any>(key, "/activity/meeting/", { query: { _limit: 25 } });
  const bookingSources = Array.from(
    new Set((meetings.data || []).map((m: any) => m.provider_calendar_type).filter(Boolean)),
  );

  const dmSet = roleLikeFields.some((f: any) => /setter|dm/i.test(f.name));

  return {
    orgId: org.id,
    orgName: org.name,
    role,
    users: { sampled: (usersPage.data || []).length, hasMore: usersPage.has_more },
    roleLikeCustomFields: roleLikeFields,
    calls: {
      sampled: cd.length,
      outbound: outbound.length,
      attributed: attributed.length,
      unattributedPct: cd.length ? Math.round((1 - attributed.length / cd.length) * 100) : 0,
      withRecording: withRecording.length,
      dispositions,
      powerDialerDetected,
    },
    recordingsAvailable: withRecording.length > 0,
    transcriptsAvailable,
    bookingSources,
    funnelType: dmSet ? "dm_set_then_dial" : "dial_in_close",
    detectedAt: Date.now(),
  };
}

/** Dev/validation: run funnel detection with a raw key. */
export const detectFunnel = internalAction({
  args: { apiKey: v.string() },
  handler: async (_ctx, args): Promise<any> => probeFunnel(args.apiKey),
});

/**
 * Self-serve connect: validate the pasted API key, characterize the funnel,
 * encrypt the key, and persist the installation. Returns a friendly error
 * string (never throws to the client) so the settings UI can render it inline.
 */
export const connectClose = action({
  args: { teamId: v.id("teams"), apiKey: v.string() },
  handler: async (
    ctx,
    args,
  ): Promise<{ success: boolean; error?: string; orgName?: string; funnel?: any }> => {
    const key = args.apiKey.trim();
    if (!key.startsWith("api_")) {
      return {
        success: false,
        error: "That doesn't look like a Close API key — it should start with \"api_\". Copy it from Close → Settings → Developer → API Keys.",
      };
    }

    // 1. Validate the key + read the org.
    let me: any;
    try {
      me = await closeFetch<any>(key, "/me/");
    } catch {
      return {
        success: false,
        error: "Close rejected this API key. Double-check you copied the full key, and that it was generated by an admin user.",
      };
    }
    const org = (me.organizations || [])[0];
    if (!org?.id) {
      return { success: false, error: "Couldn't read a Close organization from this key." };
    }

    // 2. Characterize the funnel (best-effort — don't block connect on it).
    let funnel: any = null;
    try {
      funnel = await probeFunnel(key);
    } catch {
      funnel = { orgId: org.id, orgName: org.name, detectedAt: Date.now(), partial: true };
    }

    // 3. Encrypt + persist (enforces one-CRM-per-team inside the mutation).
    const encrypted = encryptApiKey(key);
    try {
      await ctx.runMutation(internal.setterCloseInstall.upsertCloseInstallation, {
        teamId: args.teamId,
        encryptedApiKey: encrypted,
        closeOrganizationId: org.id,
        orgName: org.name,
        funnel,
      });
    } catch (e) {
      return { success: false, error: e instanceof Error ? e.message : "Failed to save the connection." };
    }

    // 4. TODO(next increment): kick off the windowed backfill (setterCloseSync).

    return { success: true, orgName: org.name, funnel };
  },
});
