// ============================================================================
// The rows behind a number.
//
// The most important file in this rebuild, and the cheapest.
//
// Three times now, this product has reported a confident figure computed from
// the wrong data and nobody could tell:
//
//   5,828 Sendblue messages fetched, 5,828 discarded — a team's dials read zero
//   while the sync reported success.
//
//   A pagination parameter GHL accepts and ignores — one location ran for WEEKS
//   believing 1,083 of its leads had never been contacted.
//
//   ~30% of calls never arriving by webhook, found only by auditing contacts
//   one at a time.
//
// Every one of those would have died in minutes if someone could have clicked
// the number and seen which rows produced it. That is all this file does: given
// a metric, hand back the exact leads, the exact timestamps, and the arithmetic
// that turned them into the figure on screen.
//
// It is also the approval step. Before a funnel goes live, the same view shows
// five real leads and says "this is what we would measure" — which is where a
// customer says "no, that text was our automation", before it becomes a number
// anyone acts on.
// ============================================================================

import { v } from "convex/values";
import { query } from "./_generated/server";
import type { Doc, Id } from "./_generated/dataModel";
import { resolveAuthUser } from "./setterGhlOauth";
import { activeFunnelFor } from "./setterFunnels";
import {
  countsChannel,
  workingHoursFor,
  elapsedWorkingMs,
} from "./setterFunnelResolve";
import { firstTouchPerLead } from "./setterMetricCompute";
import { loadWindow } from "./setterMetricRun";
import { METRICS } from "./setterMetricLibrary";

/* eslint-disable @typescript-eslint/no-explicit-any */

/** Enough to judge a number by, few enough to read. */
const SAMPLE_SIZE = 25;

export interface DrillRow {
  leadId: string;
  leadName: string;
  setterName: string | null;
  /** Every timestamp that fed the calculation, labelled in plain words. */
  steps: Array<{ label: string; at: number | null }>;
  /** The resulting figure for this one row, already in human units. */
  value: string;
  valueMs?: number;
  /** Why a row was left out, when it was. */
  excluded?: string;
}

/**
 * Which channels a lead was actually touched on, regardless of what counts.
 *
 * Shown alongside the counted touch so a manager can see the thing we ignored.
 * "We started your clock at the dial, not the text that went out 5 seconds
 * earlier" is a sentence that ends an argument; without it the number just
 * looks wrong.
 */
function describeIgnored(
  ignored: Array<{ channel: string; at: number }>,
): string | undefined {
  if (ignored.length === 0) return undefined;
  const first = ignored[0];
  return `also had an earlier ${first.channel} at ${new Date(first.at).toISOString()}, not counted by this funnel`;
}

function humanMs(ms: number | null): string {
  if (ms === null) return "—";
  const mins = ms / 60000;
  if (mins < 1) return `${Math.round(ms / 1000)}s`;
  if (mins < 90) return `${Math.round(mins)} min`;
  const hrs = mins / 60;
  if (hrs < 48) return `${hrs.toFixed(1)} hrs`;
  return `${(hrs / 24).toFixed(1)} days`;
}

/**
 * The rows behind one metric.
 *
 * Deliberately recomputes from the same functions the dashboard uses rather
 * than reading a cached explanation. An explanation generated by different code
 * to the number it explains is worse than none — it would reassure you about a
 * figure it didn't produce.
 */
export const drillMetric = query({
  args: {
    clerkId: v.string(),
    metricId: v.string(),
    rangeStart: v.number(),
    rangeEnd: v.number(),
    /** Show the slowest rather than a plain sample — where the problems are. */
    worstFirst: v.optional(v.boolean()),
  },
  handler: async (ctx, args): Promise<any> => {
    const user = await resolveAuthUser(ctx, args.clerkId);
    if (!user?.teamId) return null;
    const teamId = user.teamId as Id<"teams">;

    const metric = METRICS.find((m) => m.id === args.metricId);
    if (!metric) return { ok: false, reason: "No such metric." };

    const funnel = await activeFunnelFor(ctx, teamId);
    const team = (await ctx.db.get(teamId)) as Doc<"teams"> | null;
    const input = await loadWindow(ctx, teamId, args.rangeStart, args.rangeEnd);

    // Names, so a manager reads people and prospects rather than CRM ids.
    const reps = await ctx.db
      .query("setterReps")
      .withIndex("by_team", (q: any) => q.eq("teamId", teamId))
      .take(500);
    const repName = new Map<string, string>();
    for (const r of reps as any[]) {
      if (r.ghlUserId) repName.set(r.ghlUserId, r.name ?? r.email ?? "Unknown");
    }
    const leadRows = await ctx.db
      .query("setterLeads")
      .withIndex("by_team_and_date_added", (q: any) =>
        q
          .eq("teamId", teamId)
          .gte("dateAdded", args.rangeStart)
          .lte("dateAdded", args.rangeEnd),
      )
      .take(12_000);
    const leadName = new Map<string, string>();
    for (const l of leadRows as any[]) {
      leadName.set(
        l.ghlContactId,
        l.name || l.email || l.phone || l.ghlContactId.slice(0, 10),
      );
    }

    const isSpeed =
      metric.id === "speed_to_lead_working" || metric.id === "speed_to_lead_elapsed";

    if (isSpeed) {
      const useWorkingHours = metric.id === "speed_to_lead_working";
      const hours = useWorkingHours ? workingHoursFor(funnel, team) : null;
      const touches = (c: string) => countsChannel(funnel, c);

      // Everything a lead had, so we can show what was ignored and why.
      const byLead = new Map<string, Array<{ channel: string; at: number }>>();
      for (const e of input.events) {
        const list = byLead.get(e.leadId) ?? [];
        list.push({ channel: e.channel, at: e.occurredAt });
        byLead.set(e.leadId, list);
      }

      // Three different things that all look like "no setter", kept apart
      // because they mean completely different problems:
      //
      //   nobody       the event carries no user at all — an automation or a
      //                power dialer, which is fine and should be visible
      //   unknown      a real user id we have no rep record for — someone added
      //                to the CRM since our last sync, or a closer doing setter
      //                work. A person, just not one we can name.
      //   named        we know who it was
      //
      // Collapsing these into "None" is how you end up unable to tell an
      // automation from a colleague nobody told us about.
      let nobody = 0;
      let unknown = 0;
      const unknownIds = new Set<string>();
      // Distinct PEOPLE, as opposed to how many touches they made. Both matter
      // and they answer different questions: "how many touches came from
      // someone we can't name" is a data-quality number, "how many such people
      // are there" is the one a manager can actually go and fix.
      const namedPeople = new Set<string>();
      const nameFor = (id: string | null): string | null => {
        if (!id) {
          nobody += 1;
          return null;
        }
        const known = repName.get(id);
        if (known) {
          namedPeople.add(id);
          return known;
        }
        unknown += 1;
        unknownIds.add(id);
        return `Unrecognised user (${id.slice(0, 8)}…)`;
      };

      const pairs = firstTouchPerLead(input.leads, input.events, touches);
      const rows: DrillRow[] = pairs.map((p) => {
        const all = (byLead.get(p.leadId) ?? []).sort((a, b) => a.at - b.at);
        const ignoredEarlier = all.filter((t) => t.at < p.endMs && !touches(t.channel));
        const valueMs = elapsedWorkingMs(p.startMs, p.endMs, hours);
        return {
          leadId: p.leadId,
          leadName: leadName.get(p.leadId) ?? p.leadId.slice(0, 10),
          setterName: nameFor(p.setterId),
          steps: [
            { label: "Lead arrived", at: p.startMs },
            { label: "First counted outreach", at: p.endMs },
          ],
          value: humanMs(valueMs),
          valueMs,
          excluded: describeIgnored(ignoredEarlier),
        };
      });

      // Leads with no counted touch at all. They are excluded from speed on
      // purpose — you cannot measure a response that never happened — but
      // showing them is what stops "our speed looks great" hiding "because we
      // ignored the half we never rang".
      const touched = new Set(pairs.map((p) => p.leadId));
      const never = input.leads
        .filter((l) => !touched.has(l.leadId))
        .slice(0, 5)
        .map<DrillRow>((l) => ({
          leadId: l.leadId,
          leadName: leadName.get(l.leadId) ?? l.leadId.slice(0, 10),
          setterName: l.ownerId ? (repName.get(l.ownerId) ?? "Unrecognised user") : null,
          steps: [{ label: "Lead arrived", at: l.arrivedAt }],
          value: "never contacted",
          excluded: "no outreach on any channel this funnel counts",
        }));

      rows.sort((a, b) =>
        args.worstFirst
          ? (b.valueMs ?? 0) - (a.valueMs ?? 0)
          : a.steps[0].at! - b.steps[0].at!,
      );

      return {
        ok: true,
        metric: { id: metric.id, label: metric.label, description: metric.description },
        basis: hours
          ? `Counting only ${hours.startHour}:00-${hours.endHour}:00, ${hours.days.length} days a week (${hours.timezone}). Time outside those hours is not counted against the setter.`
          : "Counting every minute, including nights and weekends.",
        countedChannels: funnel.bindings.setterTouch?.params?.channels ?? ["call", "sms"],
        totalRows: rows.length,
        rows: rows.slice(0, SAMPLE_SIZE),
        neverContacted: { total: input.leads.length - pairs.length, sample: never },
        // Who did the work, at a glance. `nobody` is automation and is expected;
        // `unknown` means real people are doing setter work under ids we have no
        // record for, which quietly breaks every per-setter number until fixed.
        // Counts are of TOUCHES; the *People fields are distinct humans. The
        // first version reported only touches and was immediately misread as a
        // headcount, which is a fair reading of a bare number labelled
        // "setters".
        attribution: {
          namedTouches: pairs.length - nobody - unknown,
          automatedTouches: nobody,
          unrecognisedTouches: unknown,
          namedPeople: namedPeople.size,
          unrecognisedPeople: unknownIds.size,
          unrecognisedIds: [...unknownIds].slice(0, 10),
        },
        truncated: input.truncated,
      };
    }

    return {
      ok: false,
      reason: "Drill-through for this metric is not built yet.",
    };
  },
});
